spring.application.name=ticketflow
spring.datasource.url=jdbc:mysql://localhost:3306/ticketflow
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.redis.host=localhost
spring.redis.port=6379
spring.flyway.enabled=false

queue.enabled=true
queue.mode=AUTO
queue.thresholds.soft-queue=0.6
queue.thresholds.hard-queue=0.9
queue.thresholds.panic-mode=0.95
queue.weights.session=0.5
queue.weights.rps=0.3
queue.weights.db=0.2
queue.decision-ttl.hard-queue-seconds=10
queue.decision-ttl.soft-queue-seconds=30
queue.decision-ttl.no-queue-seconds=60
queue.load.max-concurrent-users=10000
queue.load.max-rps=500
queue.load.active-users-ttl-seconds=10
queue.load.rps-counter-ttl-seconds=2
queue.load.rps-shards=10
queue.load.rps-window-seconds=10