spring.application.name=ticketflow

# ---------------- DATABASE ----------------
spring.datasource.url=jdbc:mysql://localhost:3306/ticketflow
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

# ---------------- HIKARICP (IMPORTANT) ----------------
spring.datasource.hikari.pool-name=TicketFlowHikariPool
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=2000
spring.datasource.hikari.max-lifetime=1800000

# ---------------- REDIS ----------------
spring.redis.host=localhost
spring.redis.port=6379

# ---------------- SPRING SETTINGS ----------------
spring.flyway.enabled=false
spring.main.lazy-initialization=false

# ---------------- ACTUATOR + METRICS ----------------
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always

# Enable Hikari metrics
management.metrics.enable.hikari=true
  
# ---------------- RABBITMQ ----------------
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.virtual-host=/
spring.rabbitmq.connection-timeout=5000

# Custom Exchange and Queue names for your application code
spring.rabbitmq.email.exchange=ticketflow.email.exchange
spring.rabbitmq.email.queue=ticketflow.email.queue
spring.rabbitmq.email.routing-key=email.notification


# Email settings for sending booking confirmations
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=example@gmail.com
spring.mail.password=password
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.default-encoding=UTF-8

# From email address (who the email appears to be from)
ticketflow.email.from=example@gmail.com


# Quartz Scheduling
spring.quartz.job-store-type=jdbc
spring.quartz.jdbc.initialize-schema=always
